/**
* @File Name : accounthirearchycontroller.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 5, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 5, 2024 |   | Initial Version
**/

public class accounthirearchycontroller {
	@AuraEnabled
	Public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}